# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3.7'
services:
  covert_letter:
      container_name: covert_letter
      build: webservice
      environment:
        API_KEY: "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"
      labels:
        "autoheal": "true"
        Author: "https://www.linkedin.com/in/wisrovi-rodriguez/"
      ports:
         - 8501:8501
      deploy:
         resources:
           limits:
             cpus: "0.50"
             memory: 512M
           reservations:
             cpus: "0.25"
             memory: 128M
      restart: always
      privileged: true
      healthcheck:
        test: ["CMD","curl","--fail", "--head", "http://localhost:8501", "-s"]
        interval: 15s
        timeout: 5s
        retries: 5

